from _typeshed import Incomplete

md5_regex: Incomplete
sha1_regex: Incomplete
sha224_regex: Incomplete
sha256_regex: Incomplete
sha512_regex: Incomplete

def md5(value): ...
def sha1(value): ...
def sha224(value): ...
def sha256(value): ...
def sha512(value): ...
