from _typeshed import Incomplete

class ValidationFailure(Exception):
    func: Incomplete
    def __init__(self, func, args) -> None: ...
    def __unicode__(self): ...
    def __bool__(self): ...
    def __nonzero__(self): ...

def func_args_as_dict(func, args, kwargs): ...
def validator(func, *args, **kwargs): ...
